export const codeQuotes = {
    "quotes": [
      "Talk is cheap. Show me the code.",
      "Programs must be written for people to read.",
      "Good programmers write code that humans can understand.",
      "First, solve the problem. Then, write the code.",
      "Java is to JavaScript what car is to Carpet.",
      "In theory, theory and practice are the same. In practice, they’re not.",
      "Code is like humor. When you have to explain it, it’s bad.",
      "Optimism is an occupational hazard of programming.",
      "Simplicity is the soul of efficiency.",
      "Fix the cause, not the symptom.",
      "Programming isn't about what you know; it's about what you can figure out.",
      "The best error message is the one that never shows up.",
      "The most important property of a program is its user intention.",
      "The only way to learn a new language is by writing in it.",
      "Experience is the name everyone gives to their mistakes.",
      "Make it work, make it right, make it fast.",
      "Walking on water and developing software from a spec are easy if both are frozen.",
      "Deleted code is debugged code.",
      "Programming can be fun, so can cryptography; however, they should not be combined.",
      "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
      "Without requirements or design, programming is adding bugs to an empty text file.",
      "Before software can be reusable, it first has to be usable.",
      "It's not a bug – it’s an undocumented feature.",
      "The problem with troubleshooting is that trouble shoots back.",
      "A good programmer looks both ways before crossing a one-way street.",
      "Copy-and-Paste was programmed by programmers for programmers.",
      "There are only two kinds of languages: those people always complain about and those nobody uses.",
      "The best performance improvement is the transition from the nonworking state to the working state.",
      "The trouble with programmers is that you can never tell what they are doing until it’s too late.",
      "The Internet: where men are men, women are men, and children are FBI agents.",
      "Beware of bugs in the above code; I have only proved it correct, not tried it.",
      "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
      "A program is never less than 90% complete, and never more than 95% complete.",
      "Weeks of coding can save you hours of planning.",
      "To iterate is human, to recurse divine.",
      "Beta is Latin for 'still doesn’t work.'",
      "A language that doesn’t affect the way you think about programming is not worth knowing.",
      "When debugging, novices insert corrective code; experts remove defective code.",
      "If you think your users are idiots, only idiots will use it.",
      "A clever person solves a problem. A wise person avoids it.",
      "Measuring progress by lines of code is like measuring progress by weight.",
      "How does a project get to be a year late? One day at a time.",
      "Programming is like sex: one mistake and you have to support it for the rest of your life.",
      "The most beautiful code is sometimes not there at all.",
      "The function of good software is to make the complex appear simple.",
      "Simplicity carried to the extreme becomes elegance.",
      "Adding manpower to a late project makes it later.",
      "Writing code has a place in the human hierarchy worth somewhere above managing and below fingering food products.",
      "A computer once beat me at chess, but it was no match for me at kickboxing.",
      "Real programmers don’t comment their code. If it was hard to write, it should be hard to understand.",
      "When in doubt, use brute force.",
      "COBOL cripples the mind; its teaching should be a criminal offense.",
      "Any code of your own that you haven’t looked at for six or more months might as well have been written by someone else.",
      "Programming is the art of algorithm design and the craft of debugging errant code.",
      "I don't care if it works on your machine! We are not shipping your machine!",
      "Code never lies, comments sometimes do.",
      "A good way to stay flexible is to write less code.",
      "It works on my machine.",
      "One man’s crappy software is another man’s full-time job.",
      "There is no language—no matter how structured—that will prevent programmers from making bad programs.",
      "Program testing can be used to show the presence of bugs, but never to show their absence!",
      "C++: an octopus made by nailing extra legs onto a dog.",
      "One of my most productive days was throwing away 1,000 lines of code.",
      "Perl – The only language that looks the same before and after RSA encryption.",
      "When you have a hammer, everything looks like a nail.",
      "If it wasn’t hard, everyone would do it.",
      "They don't make bugs like Bunny anymore.",
      "The best way to predict the future is to invent it.",
      "Premature optimization is the root of all evil.",
      "Writing in C or C++ is like running a chainsaw with all the safety guards removed.",
      "Fools ignore complexity. Pragmatists suffer it. Some can avoid it. Geniuses remove it.",
      "A user interface is like a joke. If you have to explain it, it’s not that good.",
      "The cheapest, fastest, and most reliable components are those that aren’t there.",
      "Debugging is twice as hard as writing the code in the first place.",
      "Programming is not easy like Sunday morning, it's silent poetry.",
      "Python's a drop-in replacement for BASIC in the sense that Optimus Prime is a drop-in replacement for a truck.",
      "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics.",
      "If builders built buildings the way programmers wrote programs, the first woodpecker that came along would destroy civilization.",
      "Computers are good at following instructions, but not at reading your mind.",
      "The trouble with 'if' statements is that sometimes they really are necessary.",
      "Machine language is a soul-less zone, but as close as you get to the inner workings of the world.",
      "The goal of Computer Science is to build something that will last at least until we've finished building it.",
      "A computer program does what you tell it to do, not what you want it to do.",
      "Fast, good, cheap: pick two.",
      "It's not that I'm so smart, it's just that I stay with problems longer.",
      "Every great developer got there by solving problems they were unqualified to solve until they did it.",
      "If you have a procedure with ten parameters, you probably missed some.",
      "Software and cathedrals are much the same — first we build them, then we pray.",
      "The best programs are the ones written when the programmer is supposed to be working on something else.",
      "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
      "You can’t have great software without a great team, and most software teams behave like dysfunctional families.",
      "The difference between theory and practice is that in theory, there is no difference.",
      "Code generation, like drinking alcohol, is good in moderation.",
      "When a program is being tested, it is too late to make design changes.",
      "Code should run as fast as necessary, but no faster; something important is always traded away to increase speed.",
      "In order to understand recursion, one must first understand recursion.",
      "Computers are like air conditioners: they stop working when you open Windows.",
      "Learning to code is useful no matter what your career ambitions are.",
      "The most disastrous thing that you can ever learn is your first programming language.",
      "The best way to get a project done faster is to start sooner.",
      "It’s not a bug; it’s an undocumented feature.",
      "The computer was born to solve problems that did not exist before.",
      "Software is a great combination of artistry and engineering.",
      "The best method for accelerating a computer is the one that boosts it by 9.8 m/s2.",
      "Programming languages are like girlfriends: The new one you have now is better because you are better.",
      "I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.",
      "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
      "The best code is no code at all.",
      "In C++ it’s harder to shoot yourself in the foot, but when you do, you blow off your whole leg.",
      "It’s not a bug – it’s a feature.",
      "No one in the brief history of computing has ever written a piece of perfect software. It’s unlikely that you’ll be the first.",
      "Beware of the Turing tar-pit in which everything is possible but nothing of interest is easy.",
      "Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.",
      "To understand recursion, one must first understand recursion.",
      "The best performance improvement is the transition from the nonworking state to the working state.",
      "Computers are good at following instructions, but not at reading your mind.",
      "A language that doesn’t affect the way you think about programming is not worth knowing.",
      "Sometimes the elegant implementation is just a function. Not a method. Not a class. Not a framework. Just a function.",
      "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
      "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
      "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.",
      "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
      "Talk is cheap. Show me the code.",
      "Programs must be written for people to read, and only incidentally for machines to execute.",
      "First, solve the problem. Then, write the code.",
      "Experience is the name everyone gives to their mistakes.",
      "In order to be irreplaceable, one must always be different.",
      "The best way to get a project done faster is to start sooner.",
      "It's not a bug – it’s an undocumented feature.",
      "Walking on water and developing software from a specification are easy if both are frozen."
    ]
  }


  